# Site settings
title: Chennai Elixir User Group
email: elixir-chennai@googlegroups.com
description: The place where Elixirists can come together to share knowledge and network.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elixir-chennai.org" # the base hostname & protocol for your site
twitter_username: elixir-chennai
github_username:  elixir-chennai

# Build settings
markdown: kramdown
